[package]
name = "game_start_macro"
version = "0.1.0"
edition = "2021"
authors = ["HuaGu_Dragon"]
description = "A macro for starting a game"

[lib]
proc-macro = true
doctest = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
